/*
 * JDcambiarPass.java
 *
 * Created on 07/01/2010, 11:34:31
 */

package sgd.gui;

import java.awt.event.KeyListener;
import javax.swing.JLabel;

/**
 *
 * @author Administrador
 */
public class JDcambiarPass extends javax.swing.JDialog {

    /** Creates new form JDcambiarPass */
    public JDcambiarPass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      pass1 = new javax.swing.JPasswordField();
      jLabel1 = new javax.swing.JLabel();
      labelMsj = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      pass2 = new javax.swing.JPasswordField();
      jLabel3 = new javax.swing.JLabel();
      pass3 = new javax.swing.JPasswordField();
      jLabel5 = new javax.swing.JLabel();
      labelUsuario = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Cambio de contraseña");

      pass1.setToolTipText("Contraseña actual");
      pass1.setName("p1"); // NOI18N

      jLabel1.setText("Repetir:");

      labelMsj.setForeground(new java.awt.Color(255, 0, 51));
      labelMsj.setVerticalAlignment(javax.swing.SwingConstants.TOP);
      labelMsj.setFocusable(false);

      jLabel2.setText("Nueva:");

      pass2.setToolTipText("Nueva contraseña");
      pass2.setName("p2"); // NOI18N

      jLabel3.setText("Actual:");

      pass3.setToolTipText("Confirmación de nueva contraseña");
      pass3.setName("p3"); // NOI18N

      jLabel5.setText("Usuario:");

      labelUsuario.setFont(new java.awt.Font("Tahoma", 1, 11));
      labelUsuario.setFocusable(false);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pass2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pass3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(12, 12, 12))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(25, 25, 25)))
            .addContainerGap())
         .addComponent(labelMsj, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jLabel2)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel3))
                  .addGap(37, 37, 37)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(pass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel1)))
               .addComponent(pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(labelMsj, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel labelMsj;
   private javax.swing.JLabel labelUsuario;
   private javax.swing.JPasswordField pass1;
   private javax.swing.JPasswordField pass2;
   private javax.swing.JPasswordField pass3;
   // End of variables declaration//GEN-END:variables

    public JLabel getLabelUsuario() {        return labelUsuario;    }
    public JLabel getLabelMsj() {        return labelMsj;    }

    public String getPass1() {
        return String.valueOf(pass1.getPassword());    }

    public String getPass2() {
        return String.valueOf(pass2.getPassword());    }

    public String getPass3() {
        return String.valueOf(pass3.getPassword());    }

   public void setListener(Object o) {
        pass1.addKeyListener((KeyListener) o);
        pass2.addKeyListener((KeyListener) o);
        pass3.addKeyListener((KeyListener) o);
   }
}
