package sgd.gui.panel;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author FiruzzZ
 */
public class MiniABMPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MiniABMPanel
     */
    public MiniABMPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        cbSubTipoDocumento = new javax.swing.JComboBox();
        cbSector = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        cbInstitucion = new javax.swing.JComboBox();
        jLabelInstitucion = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Sector");

        jLabel2.setText("Tipo Documento");

        jLabel3.setText("Sub-Tipo Documento");

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EMPADRONAMIENTO", "VARIOS" }));

        cbSubTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TELEGRAMA - DENUNCIA", "TELEGRAMA - DESPIDO", "ALTA TEMPRANA", "BAJA TEMPRANA", "CONSTANCIA ALUMNO REGULAR", "PLAN MATERNO INFANTIL", "LISTA SUPER INTENDENCIA", "LISTA ANSES", "NOTAS" }));

        cbSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AFILIACIÓN", "APE", "PSICOFÍSICO", "CONTABLES", "LEGALES" }));

        jLabel4.setText("Nombre");

        cbInstitucion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINDICATO", "MUTUAL", "OS" }));

        jLabelInstitucion.setText("Institución");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabelInstitucion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoDocumento, 0, 299, Short.MAX_VALUE)
                            .addComponent(cbSubTipoDocumento, 0, 299, Short.MAX_VALUE)
                            .addComponent(cbSector, 0, 299, Short.MAX_VALUE)
                            .addComponent(cbInstitucion, 0, 299, Short.MAX_VALUE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelInstitucion)
                    .addComponent(cbInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(cbSubTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbInstitucion;
    private javax.swing.JComboBox cbSector;
    private javax.swing.JComboBox cbSubTipoDocumento;
    private javax.swing.JComboBox cbTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInstitucion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    public JComboBox getCbInstitucion() {
        return cbInstitucion;
    }

    public JComboBox getCbSector() {
        return cbSector;
    }

    public JComboBox getCbSubTipoDocumento() {
        return cbSubTipoDocumento;
    }

    public JComboBox getCbTipoDocumento() {
        return cbTipoDocumento;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTextField getTfNombre() {
        return tfNombre;
    }

    public void setVisibleSector(boolean b) {
        cbSector.setVisible(b);
        jLabel1.setVisible(b);
    }

    public void setVisibleTipoDoc(boolean b) {
        cbTipoDocumento.setVisible(b);
        jLabel2.setVisible(b);
    }

    public void setVisibleSubTipoDoc(boolean b) {
        cbSubTipoDocumento.setVisible(b);
        jLabel3.setVisible(b);
    }

    public void setVisibleNombre(boolean b) {
        tfNombre.setVisible(b);
        jLabel4.setVisible(b);
    }

    public void setVisibleInstitucion(boolean b) {
        cbInstitucion.setVisible(b);
        jLabelInstitucion.setVisible(b);
    }

    public void resetUI() {
        cbInstitucion.setSelectedIndex(0);
        cbSector.setSelectedIndex(0);
        cbTipoDocumento.setSelectedIndex(0);
        cbSubTipoDocumento.setSelectedIndex(0);
        tfNombre.setText(null);
    }
}
